routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CommentController;
use App\Http\Middleware\CheckIfArticleIsApprovable;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/articles/ajax', [ArticleController::class, 'ajaxIndex']);
Route::patch('/articles/{article}/approve', [ArticleController::class, 'approve'])->middleware(CheckIfArticleIsApprovable::class);
Route::resource('articles', ArticleController::class);

Route::get('/comments/ajax', [CommentController::class, 'ajaxIndex']);
Route::resource('comments', CommentController::class);

resources/views/_partials/_errors.blade.php
@if ($errors->any())
    <div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
        <div id="error-toast" class="toast align-items-center text-white bg-danger border-0 show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
                <div class="toast-body">
                    <ul class="mb-0">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>
    </div>

    <script>
        var toast = new bootstrap.Toast(document.getElementById('error-toast'));
        toast.show();
    </script>
@endif

@if (session('success'))
    <div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
        <div id="message-toast" class="toast align-items-center text-white bg-success border-0 show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
                <div class="toast-body">
                    {{ session('success') }}
                </div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>
    </div>

    <script>
        var toast = new bootstrap.Toast(document.getElementById('message-toast'));
        toast.show();
    </script>
@endif

resources/views/_partials/comment-card.blade.php
<div class="row text-start comment-card">
    <div class="col-2 user-section">
        {{ $comment->user->name }}
    </div>
    <div class="col-10 comment-section">
        {{ $comment->comment }}
    </div>
</div>

resources/views/_partials/form.blade.php
<form action="{{ $submitUrl }}" method="POST">
    @if ($submitMethod)
        @method($submitMethod)
    @endif

    @csrf

    @foreach ($formInputs as $name => $input)
        {{-- TODO: Move types into Enums --}}
        @switch($input['type'])
            @case('textarea')
                <div class="mb-3">
                    <label class="form-label" for="{{ $name }}">@lang("inputs.{$name}")</label>
                    <textarea class="form-control" id="{{ $name }}" name="{{ $name }}">{{ isset($item) ? $item->{$name} : null }}</textarea>
                </div>
            @break

            @case('password')
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
            @break

            @case('email')
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
            @break

            @case('checkbox')
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
            @break

            @case('foreign')
                <div class="mb-3">
                    <label class="form-label" for="{{ $name }}">@lang("inputs.{$name}")</label>
                    {{-- TODO: Use select2 for this type of inputs --}}
                    <select class="form-control" id="{{ $name }}" name="{{ $name }}">
                        @foreach ($input['related_model']::get() as $inputOption)
                            <option value="{{ $inputOption->id }}" @if (isset($item)) {{ $item->{$name} == $inputOption->id ? 'selected' : null }} @endif>{{ $inputOption->title }}</option>
                        @endforeach
                    </select>
                </div>
            @break

            @default
                <div class="mb-3">
                    <label class="form-label" for="{{ $name }}">@lang("inputs.{$name}")</label>
                    <input value="{{ isset($item) ? $item->{$name} : null }}" type="text" class="form-control" id="{{ $name }}" name="{{ $name }}"></input>
                </div>
        @endswitch
    @endforeach

    <button type="submit" class="btn btn-primary float-end">Submit</button>
</form>

resources/views/_partials/sidebar.blade.php
<!-- Sidebar -->
<div class="col-md-3 col-lg-2 sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="/home">
                    Dashboard
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                    Articles
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ route('articles.index') }}">All</a></li>
                    <li><a class="dropdown-item" href="{{ route('articles.create') }}">Create</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                    Comments
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ route('comments.index') }}">All</a></li>
                    <li><a class="dropdown-item" href="{{ route('comments.create') }}">Create</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>