routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CommentController;
use App\Http\Middleware\CheckIfArticleIsApprovable;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/articles/ajax', [ArticleController::class, 'ajaxIndex']);
Route::patch('/articles/{article}/approve', [ArticleController::class, 'approve'])->middleware(CheckIfArticleIsApprovable::class);
Route::resource('articles', ArticleController::class);

Route::get('/comments/ajax', [CommentController::class, 'ajaxIndex']);
Route::resource('comments', CommentController::class);

app/Models/Article.php
<?php

declare(strict_types=1);

namespace App\Models;

use App\Traits\HasApprovedScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Article extends Model
{
    use HasFactory, HasApprovedScope;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'user_id',
        'is_approved',
        'approved_by'
    ];

    /**
     * user
     *
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * comments
     *
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->orderBy('created_at', 'DESC');
    }
}

app/Http/Controllers/API/ArticleController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\API;

use App\Services\ArticleService;
use Illuminate\Http\JsonResponse;

class ArticleController extends BaseApiController
{
    protected ArticleService $articleService;

    public function __construct(ArticleService $articleService)
    {
        $this->articleService = $articleService;
    }

    /**
     * index
     *
     * @return JsonResponse
     */
    public function index(): JsonResponse
    {
        $data = $this->articleService->getArticlesWithPagination();

        // TODO: Use api resources for the response
        return $this->returnSuccessJsonResponse($data->toArray());
    }
}

app/Http/Controllers/ArticleController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\ArticleStoreRequest;
use App\Http\Requests\ArticleUpdateRequest;
use App\Models\Article;
use App\Services\ArticleService;
use Illuminate\Http\Request;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;


class ArticleController extends Controller
{
    protected ArticleService $articleService;

    public function __construct(ArticleService $articleService)
    {
        $this->articleService = $articleService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('articles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('articles.create', ['formInputs' => $this->articleService->getModelInputFields()]);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  ArticleStoreRequest $request
     * @return RedirectResponse
     */
    public function store(ArticleStoreRequest $request): RedirectResponse
    {
        $articleData = $request->validated() + ['user_id' => auth()->id()];

        $this->articleService->storeArticle($articleData);

        return $this->redirectSuccessResponse();
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $article = $this->articleService->findByID($id);

        return view('articles.show', ['article' => $article]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $article = $this->articleService->findByID($id, false);
        return view('articles.edit', [
            'article' => $article,
            'formInputs' => $this->articleService->getModelInputFields()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ArticleUpdateRequest $request, string $id)
    {
        $this->articleService->updateByID($id, $request->validated());
        return $this->redirectSuccessResponse();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  string $id
     * @return void
     */
    public function destroy(string $id)
    {
        $this->articleService->deleteByID($id);

        if (request()->ajax())
            return $this->returnSuccessJsonResponse();

        return $this->redirectSuccessResponse();
    }

    /**
     * ajaxIndex
     *
     * @return JsonResponse
     */
    public function ajaxIndex(): JsonResponse
    {
        $data = $this->articleService->getAjaxQueryForDatatable();

        return $this->articleService->buildAjaxDatatable($data);
    }

    /**
     * approve
     *
     * @param  mixed $article
     * @return JsonResponse
     */
    public function approve(Article $article): JsonResponse
    {
        $this->articleService->approve($article);

        return $this->returnSuccessJsonResponse();
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Control Panel</h1>
    <div class="main-content">
        @include('_partials.form', [
            'submitUrl' => route('articles.store'),
            'submitMethod' => 'POST',
        ])
    </div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1>Edit Article</h1>
    <div class="main-content">
        @include('_partials.form', [
            'submitUrl' => route('articles.update', ['article' => $article->id]),
            'submitMethod' => 'PUT',
            'item' => $article,
        ])
    </div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
@endsection

@section('content')
    <h1>Control Panel</h1>
    <div class="main-content">
        <table id="index_table" class="display">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Approved</th>
                    <th>Created at</th>
                    <th>Updated at</th>
                    <th>Actions</th>
                </tr>
            </thead>
        </table>
    </div>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script src="{{ asset('assets/js/datatables/articles.index.js') }}"></script>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.guest')

@section('content')
    <div class="main-content text-center">
        <h1>{{ $article->title }}</h1>
        <p class="text-start"><span>Created at: </span><span>{{ $article->created_at->diffForHumans() }}</span><span> ,By: </span><span>{{ $article->user->name }}</span></p>
        <p>{!! $article->description !!}</p>

        <div class="comments-section mt-5">
            <h2 class="text-decoration-underline">Comments</h2>
            @auth
                <div class="row">
                    <form class="text-start" action="{{ route('comments.store') }}" method="POST">
                        @csrf
                        <input type="hidden" name="article_id" value="{{ $article->id }}" />
                        <div class="mb-3">
                            <textarea class="form-control" id="comment" name="comment" required placeholder="Enter your comment here"></textarea>
                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary">Comment</button>
                        </div>
                    </form>
                </div>
            @endauth
            @foreach ($article->comments as $comment)
                @include('_partials.comment-card', ['comment' => $comment])
            @endforeach
        </div>
    </div>
@endsection